a = int(input("Enter a number:"))
s = int(input("Enter another number:"))
d = int(input("Enter another number:"))
w = int(input("Enter another number:"))
q = int(input("Enter another number:"))
f=(a+s+d+w+q)
print("Add", f)
g = (a-s-d-w-q)
print("Sub", g)
h = (a*s*d*w*q)
print("Multi", h)
j = (a/s/d/w/q)
print("Divide", j)