a = int(input("Enter a table"))
print(a,"ones are", a*1)
print(a,"twos are", a*2)
print(a,"threes are", a*3)
print(a,"fours are", a*4)
print(a,"fives are", a*5)
print(a,"sixes are", a*6)
print(a,"sevens are", a*7)
print(a,"eights are", a*8)
print(a,"nines are", a*9)
print(a,"tens are", a*10)